tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "autojump"
brew "coreutils"
brew "git"
brew "grc"
brew "libxmlsec1"
brew "mas"
brew "pyenv"
brew "yarn"
cask "alfred"
cask "docker"
cask "font-meslo-for-powerline"
cask "iterm2"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Divvy", id: 413857545
mas "Drafts", id: 1435957248
mas "Fantastical", id: 975937182
mas "Gifox", id: 1461845568
mas "Paste", id: 967805235
mas "Speedtest", id: 1153157709
mas "Transmit", id: 1436522307
